# Generated by Django 4.2.7 on 2025-09-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('favorite_genres', models.JSONField(blank=True, default=list)),
                ('favorite_actors', models.JSONField(blank=True, default=list)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('openness_to_new', models.IntegerField(default=5, help_text='1-10 scale')),
                ('preferred_decade', models.CharField(blank=True, max_length=10)),
                ('min_rating_threshold', models.FloatField(default=6.0)),
                ('survey_completed', models.BooleanField(default=False)),
                ('survey_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recommendations_received', models.IntegerField(default=0)),
                ('total_ratings_given', models.IntegerField(default=0)),
                ('avg_rating_given', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.profile'),
        ),
    ]
