# Generated by Django 4.2.7 on 2025-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_remove_userpreference_user_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avg_rating_given',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_actors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='min_rating_threshold',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_decade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='survey_completed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='survey_completed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_ratings_given',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_recommendations_received',
        ),
        migrations.AlterField(
            model_name='profile',
            name='openness_to_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
