# Generated by Django 4.2.7 on 2025-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_of_birth_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_actor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_loved_movie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_style',
            field=models.CharField(blank=True, choices=[('generous', 'Generous'), ('balanced', 'Balanced'), ('critical', 'Critical')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='actor_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='director_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='genre_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='least_favorite_genre',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
