# Generated by Django 4.2.7 on 2025-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='algorithm',
            field=models.CharField(default='lightfm', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version_name',
            field=models.CharField(max_length=100),
        ),
    ]
