# Generated by Django 4.2.7 on 2025-09-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_modelversion_metrics_alter_modelversion_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='learning_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='loss_function',
            field=models.CharField(default='warp', max_length=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='num_components',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='num_epochs',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='num_interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='num_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='hyperparameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='training_duration_minutes',
            field=models.FloatField(default=0.0),
        ),
    ]
